spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/yun?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://47.112.242.4:3306/yun?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    #url: jdbc:mysql://127.0.0.1:3306/dhq?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: root
#    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
          maximum-pool-size: 100
          max-lifetime: 60000
  jpa:
    show-sql: true
    properties:
      hibernate:
        #ddl-auto: update #新增数据库连接必备的参数
        format_sql: true  #自动换行

server:
  port: 8181

# jwt token签名密钥
jwt.token.secret:
  Duhongqing2020